schema_version = "1.0.0"

id = "unr_nav"
version = "0.3.2"
name = "UNR Nav"
tagline = "Enables UnrealEd 2.0 controls for Blender"
maintainer = "LunaMoca"
type = "add-on"

website = "https://lunamoca.net"

tags = ["3D View","Camera"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "linux-x64"]